### ISSUE TITLE
QVina2 vs Vina 1.2.0

### ISSUE THREAD

**Issue by DarthSaddest** [QVina/qvina#11]
If I am not bothered with the gain in computational time, what other advantages shall I expect from QVina 2 over [Vina 1.2.0](https://pubs.acs.org/doi/10.1021/acs.jcim.1c00203)? I am not inclined to think that the [increased reliability](https://academic.oup.com/bioinformatics/article/31/13/2214/195750) persists anymore.

**Comment by aalhossary** [comment]
I did not have the chance yet to study what `Vina 1.2.0` provides to answer your question, but I am pretty sure Vina 1.2.0 is a great piece of scientific work built in 2021.

If you are asking about `QuickVina-W`, the answer is defiantly the ability of blind docking on wide search space.
