### ISSUE TITLE
Problem with a ZINC15 ligand ZINC000170910319

### ISSUE THREAD

**Issue by xavgit** [QVina/qvina#13]
Hi,
when I use quickvina2 with the ligand ZINC000170910319 I receive the following:

$ qvina2 --config docking_conf_vina_1.txt 
\############################################################################
\# If you used Quick Vina 2 in your work, please cite:                      #
\#                                                                          #
\# Amr Alhossary, Stephanus Daniel Handoko, Yuguang Mu, and Chee-Keong Kwoh,#
\# Fast, Accurate, and Reliable Molecular Docking with QuickVina 2,         #
\# Bioinformatics (2015), doi: 10.1093/bioinformatics/btv082                #
\#                                                                          #
\# You are also encouraged to cite Quick Vina 1:                            #
\# Stephanus Daniel Handoko, Xuchang Ouyang, Chinh Tran To Su, Chee Keong   #
\# Kwoh, Yew Soon Ong,                                                      #
\# QuickVina: Accelerating AutoDock Vina Using Gradient-Based Heuristics for#
\# Global Optimization,                                                     #
\# IEEE/ACM Transactions on Computational Biology and Bioinformatics,vol.9, #
\# no. 5, pp. 1266-1272, Sept.-Oct. 2012, doi: 10.1109/TCBB.2012.82         #
\#                                                                          #
\# and original AutoDock Vina paper:                                        #
\# O. Trott, A. J. Olson,                                                   #
\# AutoDock Vina: improving the speed and accuracy of docking with a        #
\# new scoring function, efficient optimization and multithreading,         #
\# Journal of Computational Chemistry 31 (2010) 455-461                     #
\# doi: 10.1002/jcc.21334                                                   #
\############################################################################

Output will be ./zinc15_ligs_1/ZINC000170910319_out.pdbqt
Detected 32 CPUs
Reading input ... 

Parse error on line 71 in file "./zinc15_ligs_1/ZINC000170910319.pdbqt": ATOM syntax incorrect: "CG0" is not a valid AutoDock type. Note that AutoDock atom types are case-sensitive.

If I use vina v1.2.3  with the same receptor and ligand all works fine as can be seen fron the following:

$ time vina --config docking_conf_vina_1.txt 
AutoDock Vina v1.2.3
\#################################################################
\# If you used AutoDock Vina in your work, please cite:          #
\#                                                               #
\# J. Eberhardt, D. Santos-Martins, A. F. Tillack, and S. Forli  #
\# AutoDock Vina 1.2.0: New Docking Methods, Expanded Force      #
\# Field, and Python Bindings, J. Chem. Inf. Model. (2021)       #
\# DOI 10.1021/acs.jcim.1c00203                                  #
\#                                                               #
\# O. Trott, A. J. Olson,                                        #
\# AutoDock Vina: improving the speed and accuracy of docking    #
\# with a new scoring function, efficient optimization and       #
\# multithreading, J. Comp. Chem. (2010)                         #
\# DOI 10.1002/jcc.21334                                         #
\#                                                               #
\# Please see https://github.com/ccsb-scripps/AutoDock-Vina for  #
\# more information.                                             #
\#################################################################

Output will be ./zinc15_ligs_1/ZINC000170910319_out.pdbqt
Scoring function : vina
Rigid receptor: receptor.pdbqt
Ligand: ./zinc15_ligs_1/ZINC000170910319.pdbqt
Grid center: X 112.7 Y 109.3 Z 113.165
Grid size  : X 20.71 Y 19.73 Z 16.24
Grid space : 0.375
Exhaustiveness: 32
CPU: 0
Verbosity: 1

Computing Vina grid ... done.
Performing docking (random seed: -1790117891) ... 
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
\***************************************************

mode |   affinity | dist from best mode
     | (kcal/mol) | rmsd l.b.| rmsd u.b.
-----+------------+----------+----------
   1       -9.032          0          0
   2       -8.974      2.744      6.242
   3        -8.94      1.944      3.354
   4       -8.938      1.828      2.786
   5       -8.876      2.893        5.2

real	0m41,052s
user	18m34,348s
sys	0m0,868s

It is possible to fix this?
Thanks.
Saverio

**Comment by xavgit** [comment]
Hi,
the pdbqt converted file that gives the problem is:
 
[ZINC000170910319.pdbqt.txt](https://github.com/QVina/qvina/files/11025410/ZINC000170910319.pdbqt.txt)
Thanks.
Saverio

**Comment by aalhossary** [comment]
QVina depends on Vina 1.1.2.
which does not know the new (expanded) forcefield. If you like to compile the new definitions file and submit a pull request, it would be highly appreciated
