### ISSUE TITLE
ATOM syntax incorrect: "CG0" is not a valid AutoDock type.

### ISSUE THREAD

**Issue by SawanKumar23** [QVina/qvina#18]
I have downloaded the 3D conformer of Galantamine from Pubchem and converted the Galantamine.sdf file to a pdbqt file using the mk_perpare_ligand.py script. Now, during docking through qvina2.1, this error is shown.
ATOM syntax incorrect: "CG0" is not a valid AutoDock type. Note that AutoDock atom types are case-sensitive.
Docking failed.
How do we deal with this atom-type error? Please provide assistance on this.
The below is the prepared pdbqt file.
[gnt_pdbqt.txt](https://github.com/user-attachments/files/17743139/gnt_pdbqt.txt)

**Comment by Ritzhi-San** [comment]
Your .pdbqt file is structured incorrectly.

Suggested fixes:
1) Convert your .SDF file to .PDB first via openbabel, then use Autodock Tools 1.5.6 to create the ligand .pdbqt file. (the mk_prepare_ligand.py script only works on .pdb files from what i understand)

2) Directly convert your source .SDF file to .PDBQT via openbabel (risky, there is a high chance that the file structure may be messed up as well, openbabel while great isnt perfect)

3) Use PyMol to create a .PDB file from your .SDF file (Requires a bit of know how, ChatGPT may help). Then use Autodock Tools 1.5.6 to get your ligand .PDBQT file.

At the end you want to make sure your file is called gnt.pdbqt and has a structure identical to whats shown below:

```
REMARK  0 active torsions:
REMARK  status: ('A' for Active; 'I' for Inactive)
REMARK       I    between atoms: O5'_2  and  C5'_3 
REMARK       I    between atoms: C5'_3  and  C4'_4 
REMARK       I    between atoms: C1'_6  and  N1_7 
REMARK       I    between atoms: C4_12  and  N4_13 
REMARK       I    between atoms: C2'_17  and  O2'_18 
REMARK       I    between atoms: C3'_20  and  O3'_21 
REMARK       I    between atoms: O3'_21  and  P_22 
ROOT
ATOM      1 'HO5  DC A   1      -0.514  -1.135  -0.066  1.00  0.00     0.209 HD
ATOM      2  O5'  DC A   1      -0.267  -0.305  -0.480  1.00  0.00    -0.398 OA
ATOM      3  C5'  DC A   1       1.100  -0.053  -0.137  1.00  0.00     0.198 C 
ATOM      4  C4'  DC A   1       1.279  -0.002   1.363  1.00  0.00     0.180 C 
ATOM      5  O4'  DC A   1       1.126   1.376   1.806  1.00  0.00    -0.353 OA
ATOM      6  C1'  DC A   1       0.348   1.413   2.990  1.00  0.00     0.264 C 
ATOM      7  N1   DC A   1      -0.946   2.043   2.680  1.00  0.00    -0.278 N 
ATOM      8  C6   DC A   1      -1.375   2.172   1.388  1.00  0.00     0.102 A 
ATOM      9  C2   DC A   1      -1.738   2.507   3.734  1.00  0.00     0.352 A 
ENDROOT
TORSDOF 415
```

Dont copy this file, its just an example, but if you see a formatted structure identical to this when opening the .pdbqt file on Notepad/VScode, you are on the right track.

**Comment by aalhossary** [comment]
@SawanKumar23 Did @Ritzhi-San answer your question?
I will close the issue. If it was not enough to answer your question, please reopen it again.
