### ISSUE TITLE
Clarification about uploaded binaries

### ISSUE THREAD

**Issue by hadim** [QVina/qvina#6]
It's not clear from where the uploaded binaries in `bin/` come from.

In the makefile, there is two targets `all: vina vina_split` which I guess corresponds to the binaries in `bin/` ?

From where do the other binaries come from?

It would be helpful to have a consolidated repo where every binary each generate using a single Makefile or using CMake for example. I am happy to submit a PR if someone can provide me some guidance.

**Comment by hadim** [comment]
ping @aalhossary

**Comment by aalhossary** [comment]
Dear Hadrien Mary,
I guess you are using the master branch. This will produce AutoDock Vina.

Please consider switching to either branches, as in these pages:
https://qvina.github.io/compilingQvina2.html
https://qvina.github.io/compilingQvina-w.html

Please don’t hesitate to contact me for any further inquiries.

Regards

Amr

**Comment by hadim** [comment]
Thank you for your answer. Here is a proposal to reorganize the code: https://github.com/QVina/qvina/pull/7
